client_config_backend: settings
client_config:
  client_id: {{636394371423-hji80sgsr117l57hu1vbsjl73jg8440t.apps.googleusercontent.com}}
  client_secret: {{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}}

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope: 
  - https://www.googleapis.com/auth/drive.file